branches: main
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/git'
    - assets:
        - dist/**/*.{cjs,mjs,d.ts}
        - package.json
      message: |-
        chore(release): ${nextRelease.version} [skip ci]

        ${nextRelease.notes}
  - - '@semantic-release/github'
    - assets:
        - path: dist/module.cjs
          label: CommonJS
        - path: dist/module.mjs
          label: ES Module
        - path: dist/module.d.ts
          label: TypeScript Definitions
  - '@semantic-release/npm'
